Feature/RI-1680
A2O-Dev/django-app pull request #1
Opened 2024-07-04 15:17 UTC by alvaroia2odev

2024-07-04 17:26 UTC, cancioalmaraza2o commented
@alvaroia2odev veo que no has actualizado la dockerización.

La imagen sigue siendo la misma.

Tienes que mover el Dockerfile a la raiz del proyecto y hacer que la app funcione directamente con esa imagen construida.

Esta imagen que vayas a construir tiene que estar basada en python alpine.

El uso que has hecho de una imagen de terceros es incorrecto, arregla todo esto

2024-07-04 17:26 UTC, cancioalmaraza2o requested changes

2024-07-04 17:26 UTC, cancioalmaraza2o commented on k8s/03-app-deployment.yaml
> +          image: salt/django-mariadb:1.0.0
aquí debería usar la imagen build subida al repo: a2odev/django-app-demo

Y esa imagen tiene que estar basada en la imagen python alpine

2024-07-04 17:26 UTC, cancioalmaraza2o commented on docker-compose.yml
El docker-compose tiene que estar enfocado al desarollo solamente, no al despliegue

2024-07-05 16:30 UTC, alvaroia2odev commented
Se han realizado los cambios solicitados.

2024-07-05 17:08 UTC, cancioalmaraza2o requested changes

2024-07-05 17:08 UTC, cancioalmaraza2o commented on k8s/01-secrets.yaml.example
> +  name: django-app-demo-secrets
Nombre redundant, eliminar "secrets"

2024-07-05 17:08 UTC, cancioalmaraza2o commented on k8s/02-config.yaml
Este archivo no es innecesario? Eliminarlo

2024-07-05 17:08 UTC, cancioalmaraza2o commented on k8s/05-nginx-deployment copy.yaml
Este archivo tambien es necesario?

2024-07-05 17:15 UTC, alvaroia2odev commented
Se han realizado los cambios

2024-07-05 17:52 UTC, cancioalmaraza2o requested changes

2024-07-05 17:52 UTC, cancioalmaraza2o commented on k8s/03-database-deployment.yaml
> +                name: django-app-demo-secrets
Cambiaste el nombre de los secrets, estas seguro que funciona?

2024-07-05 18:05 UTC, alvaroia2odev commented
Arreglado y funcionando correctamente.

2024-07-05 18:33 UTC, cancioalmaraza2o approved these changes

2024-07-05 18:33 UTC, merged